export enum DateOfPublication {
  OneDay = "Hace 1 día",
  TwoDays = "Hace 2 días",
  ThreeDays = "Hace 3 días",
  FourDays = "Hace 4 días",
  FiveDays = "Hace 5 días",
  SixDays = "Hace 6 días",
  SevenDays = "Hace 7 días",
  OneWeek = "Hace 1 semana",
  TwoWeeks = "Hace 2 semanas",
  ThreeWeeks = "Hace 3 semanas",
  OneMonth = "Hace 1 mes",
  TwoMonths = "Hace 2 meses",
  ThreeMonths = "Hace 3 meses",
  FourMonths = "Hace 4 meses",
  FiveMonths = "Hace 5 meses",
  SixMonths = "Hace 6 meses",
  SevenMonths = "Hace 7 meses",
  EightMonths = "Hace 8 meses",
}
