export enum Icon {
  Arrow = 'arrow',
  Camera = 'camera',
  Delete = 'delete',
  Edit = 'edit',
  Exchanges = 'exchanges',
  Hand = 'hand',
  Home = 'home',
  Logout = 'logout',
  Profile = 'profile',
  Publication = 'publication',
  Save = 'save',
  Search = 'search',
  Star = 'star',
  State = 'state',
}
